### ISSUE TITLE
this.$refs.tcPlayer.vTcPlayer获取不到实例

### ISSUE THREAD

**Issue by 763994613** [vonweb/v-tcplayer#1]
RT  使用
computed: {
    player () {
      // tcPlayer实例
      return this.$refs.tcPlayer.vTcPlayer
    }
  }
没有获取到对应的实例对象，烦请确认一下

**Comment by 763994613** [comment]
已解决，感谢分享

**Comment by vonweb** [comment]
不好意思，好久没有管这个项目了
